[package]
name = "backend-core"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
env_logger = "0.11"
futures = "0.3"
http = "1.1"
itertools = "0.13"
log = "0.4"
rust_decimal = { version = "1.36", features = ["serde-with-arbitrary-precision"] }
rust_decimal_macros = "1.36"
sea-orm = { version = "1.0", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.26"
strum_macros = "0.26"
thiserror = "2.0"
tokio = { version = "1.40", features = ["rt", "macros"] }
uuid = { version = "1.10", features = ["serde", "v4", "macro-diagnostics"] }

[dev-dependencies]
anyhow = "1.0"
rust_decimal_macros = "1.36"
sea-orm = { version = "1.0", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
test-suite = { path = "../test-suite" }
